# https://github.com/FabricMC/fabric-example-mod/blob/06e3e43ee0662fd1afecebb428cb04cdc271b0ab/.github/workflows/build.yml
# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  pull_request:
    branches:
      - '*'
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        # 21 -> Current Java LTS & minimum supported by Minecraft
        java: [21]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
