name: Publish Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: Set mod version
        id: mod_version
        run: |
          MOD_VERSION=$(grep 'mod_version' gradle.properties | cut -f2- -d= | sed -e 's/^[[:space:]]*//')
          echo "::set-output name=MOD_VERSION::$MOD_VERSION"

      - name: Create new releases for GitHub, Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: Simple HUD Utilities ${{ steps.mod_version.outputs.MOD_VERSION }}
          github-generate-changelog: true
          github-discussion: Announcements
